# Generated by Django 2.1.5 on 2019-01-31 06:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Notes', '0003_auto_20190130_0925'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notes',
            name='collaborate',
        ),
        migrations.AddField(
            model_name='notes',
            name='collaborate',
            field=models.ManyToManyField(blank=True, null=True, related_name='collaborated_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
