# Generated by Django 2.1.5 on 2019-02-16 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Notes', '0005_auto_20190206_0427'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notes',
            name='label',
        ),
    ]
