# Generated by Django 2.1.5 on 2019-02-23 13:07

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Notes', '0008_auto_20190223_0455'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='reminder',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 23, 13, 7, 23, 453145, tzinfo=utc), null=True),
        ),
    ]
