# Generated by Django 2.1.5 on 2019-02-26 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Notes', '0014_auto_20190226_0947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='reminder',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
