# Generated by Django 2.1.5 on 2019-02-28 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Notes', '0015_auto_20190226_1057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='title',
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
