# Generated by Django 2.1.5 on 2019-03-02 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Notes', '0016_auto_20190228_1255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='title',
            field=models.CharField(max_length=150),
        ),
    ]
