# Generated by Django 2.1.5 on 2019-02-05 04:57

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Notes', '0004_auto_20190131_0655'),
        ('Labels', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MapLabels',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('label_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Labels.Labels')),
                ('note_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Notes.Notes')),
            ],
        ),
    ]
