# Generated by Django 2.1.5 on 2019-02-06 04:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Notes', '0005_auto_20190206_0427'),
        ('Labels', '0002_maplabels'),
    ]

    operations = [
        migrations.AddField(
            model_name='labels',
            name='note_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Notes.Notes'),
        ),
    ]
