# Generated by Django 2.1.5 on 2019-02-06 04:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Labels', '0003_labels_note_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maplabels',
            name='label_id',
        ),
        migrations.RemoveField(
            model_name='maplabels',
            name='note_id',
        ),
        migrations.DeleteModel(
            name='MapLabels',
        ),
    ]
