# Generated by Django 2.1.5 on 2019-02-06 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Labels', '0004_auto_20190206_0428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labels',
            name='label',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
