# Generated by Django 2.1.5 on 2019-02-08 05:03

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Notes', '0005_auto_20190206_0427'),
        ('Labels', '0005_auto_20190206_1112'),
    ]

    operations = [
        migrations.CreateModel(
            name='MapLabels',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.RemoveField(
            model_name='labels',
            name='note_id',
        ),
        migrations.AddField(
            model_name='maplabels',
            name='label_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Labels.Labels'),
        ),
        migrations.AddField(
            model_name='maplabels',
            name='note_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Notes.Notes'),
        ),
    ]
